### ISSUE TITLE
make latexpdf error

### ISSUE THREAD

**Issue by adammaj1** [tatsy/lime#7]
Hi, 
after makelatex  I have an error

`a@zelman:~/lime/docs$ make latexpdf
sphinx-build -b latex -d build/doctrees   source build/latex
Running Sphinx v1.6.7
making output directory...
0.3.0

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/a/.local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 140, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme

Makefile:139: recipe for target 'latexpdf' failed
make: *** [latexpdf] Error 1
`

Any tips
TIA

Adam

**Comment by tatsy** [comment]
You need sphinx_rtd_theme to be installed through Python pip. Before asking with Issue, you must see the error message carefully, please!
